// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApjFKjxO3ssaWI242oI8UbFXOSh57TJ3k',
    appId: '1:520247866985:web:acf87f6f65b99402ba54f8',
    messagingSenderId: '520247866985',
    projectId: 'movie-app-12x',
    authDomain: 'movie-app-12x.firebaseapp.com',
    storageBucket: 'movie-app-12x.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHbRTbqLyV0RA2WI8RYNVy5qDBkXcvLQw',
    appId: '1:520247866985:android:19452f110e3ebb7cba54f8',
    messagingSenderId: '520247866985',
    projectId: 'movie-app-12x',
    storageBucket: 'movie-app-12x.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA71xRNH2d5xrzHRe2aYKo-5zvDf_5Lm_c',
    appId: '1:520247866985:ios:4a2a27287ec08b71ba54f8',
    messagingSenderId: '520247866985',
    projectId: 'movie-app-12x',
    storageBucket: 'movie-app-12x.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA71xRNH2d5xrzHRe2aYKo-5zvDf_5Lm_c',
    appId: '1:520247866985:ios:4a2a27287ec08b71ba54f8',
    messagingSenderId: '520247866985',
    projectId: 'movie-app-12x',
    storageBucket: 'movie-app-12x.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApjFKjxO3ssaWI242oI8UbFXOSh57TJ3k',
    appId: '1:520247866985:web:68fb251d795f46e9ba54f8',
    messagingSenderId: '520247866985',
    projectId: 'movie-app-12x',
    authDomain: 'movie-app-12x.firebaseapp.com',
    storageBucket: 'movie-app-12x.firebasestorage.app',
  );
}
